resources:
  containers:
  - container: ubuntu1804
    image: yugabytedb/yb_build_infra_ubuntu1804:v2019-04-30T20_16_36_mikhail
  - container: centos7
    image: yugabytedb/yb_build_infra_centos7:v2019-04-30T20_16_52_mikhail

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-16.04'
  timeoutInMinutes: 0

  strategy:
    matrix:
      #ubuntu1804:
      #  containerResource: ubuntu1804
      centos7:
        containerResource: centos7

  container: $[ variables['containerResource'] ]

  steps:
    - script: |
        set -euxo pipefail
        repo_dir=$PWD
        tag=v0.$( git rev-list --count HEAD )
        mkdir ~/linuxbrew_versions
        cd ~/linuxbrew_versions
        "$repo_dir/linuxbrew-clone-and-build-all.sh"
        create_release_cmd=( hub release create "$tag" -m "Release $tag" )
        for release_artifact in *.tar.gz; do
          create_release_cmd+=( -a "$PWD/$release_artifact" )
        done
        cd "$repo_dir"
        "${create_release_cmd[@]}"
      env:
        GITHUB_TOKEN: $(yugabyte.githubToken)
