
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get install -y build-essential
  displayName: 'Install dependencies'

- script: |
    repo_dir=$PWD
    mkdir ~/linuxbrew_versions
    cd ~/linuxbrew_versions
    "$repo_dir/linuxbrew-clone-and-build-all.sh"
  displayName: 'Build Linuxbrew'

timeoutInMinutes: 0
